apiVersion: v1
kind: Pod
metadata:
  name: todolist-web
  labels:
    name: todolist-web
spec:
  containers:
  - name: todolist-web
    image: jouryjc/todolist-web
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/default.conf
    ports:
      - containerPort: 80
  volumes:
    - name: nginx-conf
      hostPath:
        path: /home/demo/nginx-default.conf
