name: build
on:
  push:
    branches:
      - "master"

env:
  DOCKERHUB_USERNAME: jouryjc

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build todolist server and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/todolist-server:${{ steps.vars.outputs.sha_short }}
      - name: Build todolist web and push
        uses: docker/build-push-action@v3
        with:
          context: web
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/todolist-web:${{ steps.vars.outputs.sha_short }}