// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxForm: typeof import('@idux/components/form')['IxForm']
    IxFormItem: typeof import('@idux/components/form')['IxFormItem']
    IxInput: typeof import('@idux/components/input')['IxInput']
    IxModalProvider: typeof import('@idux/components/modal')['IxModalProvider']
    IxNotificationProvider: typeof import('@idux/components/notification')['IxNotificationProvider']
    IxSelect: typeof import('@idux/components/select')['IxSelect']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    IxTable: typeof import('@idux/components/table')['IxTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
